version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: todo-app-db
    environment:
      POSTGRES_DB: todo_app_db
      POSTGRES_USER: todo_app_user
      POSTGRES_PASSWORD: tboF6xnttczii5O80PBIrBgj
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo_app_user -d todo_app_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
